CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username VARCHAR(255),
    order_date TIMESTAMP,
    status VARCHAR(255),
    total_amount NUMERIC(19, 2),
    payment_id BIGINT
);

CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(255),
    product_name VARCHAR(255),
    quantity INTEGER,
    price_at_time_of_purchase NUMERIC(19, 2),
    order_id BIGINT,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE INDEX idx_orders_user_id ON orders (user_id);
CREATE INDEX idx_order_item_order_id ON order_item (order_id);
