CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(255),
    amount NUMERIC(19, 2),
    currency VARCHAR(255),
    payment_method VARCHAR(255),
    status VARCHAR(255),
    payment_date TIMESTAMP,
    transaction_id VARCHAR(255)
);

CREATE INDEX idx_payment_order_id ON payment (order_id);
